name: smartfarm
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  url_launcher: ^6.3.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/smartfarm_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/smartfarm_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/premium.jpeg
    - assets/images/smartfarm_icon.png
    - assets/images/farmlogo.png
    - assets/video/background.mp4
    - .env
