// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwEz--ouv7WHbmgrJAoY8_tSQsfCauqc',
    appId: '1:823316443657:web:8be5f13f5ac86bbad5bed8',
    messagingSenderId: '823316443657',
    projectId: 'agrita-2c5d6',
    authDomain: 'agrita-2c5d6.firebaseapp.com',
    storageBucket: 'agrita-2c5d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcLZ0MAd0AFGwGwsjIOiU5v9acUcr27GQ',
    appId: '1:823316443657:android:64b0e81a514b770fd5bed8',
    messagingSenderId: '823316443657',
    projectId: 'agrita-2c5d6',
    storageBucket: 'agrita-2c5d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg0wKhdFmgXNDJJ-rL1Nb-CNrXonKzzNQ',
    appId: '1:823316443657:ios:13da0f82bf5a0177d5bed8',
    messagingSenderId: '823316443657',
    projectId: 'agrita-2c5d6',
    storageBucket: 'agrita-2c5d6.firebasestorage.app',
    iosBundleId: 'com.agrita.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg0wKhdFmgXNDJJ-rL1Nb-CNrXonKzzNQ',
    appId: '1:823316443657:ios:9eb9bd8c901cc8bed5bed8',
    messagingSenderId: '823316443657',
    projectId: 'agrita-2c5d6',
    storageBucket: 'agrita-2c5d6.firebasestorage.app',
    iosBundleId: 'com.example.smartfarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzwEz--ouv7WHbmgrJAoY8_tSQsfCauqc',
    appId: '1:823316443657:web:655448452274009ed5bed8',
    messagingSenderId: '823316443657',
    projectId: 'agrita-2c5d6',
    authDomain: 'agrita-2c5d6.firebaseapp.com',
    storageBucket: 'agrita-2c5d6.firebasestorage.app',
  );
}
